CREATE DATABASE IF NOT EXISTS proyecto1;

USE proyecto1;

-- CREACION DE TABLAS INDEPENDIENTES

CREATE TABLE IF NOT EXISTS CIUDADANO (
    dpi VARCHAR(13) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    apellido VARCHAR(30) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(10) NOT NULL,
    edad INTEGER NOT NULL,
    genero VARCHAR(1) NOT NULL,
    PRIMARY KEY (dpi)
);

CREATE TABLE IF NOT EXISTS CARGO (
    id_cargo INTEGER NOT NULL,
    cargo VARCHAR(40) NOT NULL,
    PRIMARY KEY (id_cargo)
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    id_departamento INTEGER NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    PRIMARY KEY (id_departamento)
);

CREATE TABLE IF NOT EXISTS PARTIDO (
    id_partido INTEGER NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    siglas VARCHAR(20) NOT NULL,
    fundacion DATE NOT NULL,
    PRIMARY KEY (id_partido)
);

-- CREACION DE TABLAS DEPENDIENTES

CREATE TABLE IF NOT EXISTS MESA (
    id_mesa INTEGER NOT NULL,
    id_departamento INTEGER NOT NULL,
    PRIMARY KEY (id_mesa),
    CONSTRAINT FOREIGN KEY (id_departamento) REFERENCES DEPARTAMENTO(id_departamento)
);

CREATE TABLE IF NOT EXISTS VOTO (
    id_voto INTEGER NOT NULL,
    fecha_hora DATETIME NOT NULL,
    dpi VARCHAR(13) NOT NULL,
    id_mesa INTEGER NOT NULL,
    PRIMARY KEY (id_voto),
    CONSTRAINT FOREIGN KEY (dpi) REFERENCES CIUDADANO(dpi),
    CONSTRAINT FOREIGN KEY (id_mesa) REFERENCES MESA(id_mesa)
);

CREATE TABLE IF NOT EXISTS CANDIDATO (
    id_candidato INTEGER NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    fecha_nac DATETIME NOT NULL,
    id_cargo INTEGER NOT NULL,
    id_partido INTEGER NOT NULL,
    PRIMARY KEY (id_candidato),
    CONSTRAINT FOREIGN KEY (id_cargo) REFERENCES CARGO(id_cargo),
    CONSTRAINT FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido)
);

CREATE TABLE IF NOT EXISTS DETALLE_VOTO (
    id_detalle_voto INTEGER NOT NULL,
    id_voto INTEGER NOT NULL,
    id_candidato INTEGER NOT NULL,
    PRIMARY KEY (id_detalle_voto),
    CONSTRAINT FOREIGN KEY (id_voto) REFERENCES VOTO(id_voto),
    CONSTRAINT FOREIGN KEY (id_candidato) REFERENCES CANDIDATO(id_candidato)
);